baseURL = 'https://www.sydneytech.org'
languageCode = 'en-us'
title = 'Sydney Tech Blog'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[params.media]
  # Assuming you attach the custom domain 'media.sydneytech.org' to your R2 bucket
  r2BaseUrl = "https://media.sydneytech.org"
